update Docker build stage code in pipeline_app file.

diff --git a/pipeline_app.yml b/pipeline_app.yml
--- a/pipeline_app.yml
+++ b/pipeline_app.yml
@@ -40,6 +40,10 @@ stages:
         echo "DEBUG: Value of DOCKER_REPO: '${DOCKER_REPO}'"
         echo "DEBUG: Value of BUILD_TAG: '${BUILD_TAG}'"
         echo "DEBUG: Value of Build.BuildId directly: '$(Build.BuildId)'"
+         if [ -z "${BUILD_TAG}" ]; then
+          echo "ERROR: BUILD_TAG is empty! Aborting Docker build and push."
+          exit 1
+        fi
         sudo docker build -t ${Docker_repo}:${Build_tag} .
         sudo docker push ${Docker_repo}:${Build_tag}
         sudo docker tag ${Docker_repo}:${Build_tag} ${Docker_repo}:latest
